#define PLOT_DATA_FILE "q3_experimental_data.dat"
#define PLOT_OUTPUT_FILE "q3_evidence.svg"
#define PLOT_TITLE "Q3 | Longest common subsequence"
#define PLOT_SUBTITLE "prefix-pair states recorded in C; answers independently checked"
#define PLOT_BADGE "LAB 08 / MEASURED"
#define PLOT_X_LABEL "Input scale (log2 axis)"
#define PLOT_FOOTER "Deterministic inputs. Counters measure operations, not elapsed time."
#define PLOT_REFERENCE_LABEL "exact work reference"
#include "../common/plot_from_dat.h"
