#define PLOT_DATA_FILE "q8_experimental_data.dat"
#define PLOT_OUTPUT_FILE "q8_evidence.svg"
#define PLOT_TITLE "Q8 | Optimal search trees"
#define PLOT_SUBTITLE "candidate roots recorded in C; answers independently checked"
#define PLOT_BADGE "LAB 08 / MEASURED"
#define PLOT_X_LABEL "Input scale (log2 axis)"
#define PLOT_FOOTER "Deterministic inputs. Counters measure operations, not elapsed time."
#define PLOT_REFERENCE_LABEL "exact work reference"
#include "../common/plot_from_dat.h"
