#define PLOT_DATA_FILE "q2_experimental_data.dat"
#define PLOT_OUTPUT_FILE "q2_evidence.svg"
#define PLOT_TITLE "Q2 | Coin combinations"
#define PLOT_SUBTITLE "checked DP additions recorded in C; answers independently checked"
#define PLOT_BADGE "LAB 08 / MEASURED"
#define PLOT_X_LABEL "Input scale (log2 axis)"
#define PLOT_FOOTER "Deterministic inputs. Counters measure operations, not elapsed time."
#define PLOT_REFERENCE_LABEL "cV upper envelope"
#include "../common/plot_from_dat.h"
