"""Shared, source-grounded explanations for READMEs and compact reports."""
PROBLEMS=[
 'Given base values, weights and positive decay rates, choose a consumption order and fractions within capacity W to maximise total effective value. Density at time t is v/w - lambda*t.',
 'Given symbol frequencies, construct a prefix-free binary code with minimum expected length and output a canonical Huffman codebook ordered by length, then symbol.',
 'Reach target distance D starting with fuel F. Station (d, f) gives f additional fuel at distance d. Find the minimum number of refuelling stops, or report impossibility.',
 'Connecting sticks of lengths x and y costs x+y and produces a stick of length x+y. Find the minimum total cost of connecting all sticks into one.',
 'Give each child at least one candy. A child with a higher rating than an immediate neighbour must receive more candies. Find the minimum total and an allocation.',
 'Rearrange a string so equal characters occur at positions at least K apart. Return an empty string when no rearrangement exists.',
 'For positive integers, multiply an odd element by two or divide an even element by two any number of times. Minimise maximum minus minimum and return a legal witness.',
 'Assign meetings to the minimum number of rooms. Meetings use half-open intervals [start,end); a room may be reused when its previous meeting ends.',
 'Construct an optimal alphabetic leaf tree for ordered positive weights, preserving the in-order leaf sequence and minimising the sum of weight times leaf depth.',
 'Explore shortest common superstrings and the maximum-overlap greedy heuristic. Compare its result with an exact optimum on small inputs; discuss the supplied conjecture claim carefully.'
]
INPUTS=[
 '`n W`, followed by n rows `value weight decay_rate`. n = 1..8; W and value = 0..10000; weight and rate = 0.001..10000. Real numbers are allowed.',
 '`n`, followed by n rows `symbol frequency`. Symbols are distinct printable non-space ASCII except double quote and backslash; frequencies = 1..10^9. There are 92 supported symbols. Omit zero-frequency symbols.',
 '`n D F`, followed by n rows `distance fuel`. n = 0..100000; D, F and fuel = 0..10^9; station distance = 0..D. Stations may be unsorted. One fuel unit covers one distance unit; tank capacity is unlimited.',
 '`n`, followed by n positive lengths. n = 0..100000; length = 1..10^9. An empty or singleton collection costs zero.',
 '`n`, followed by n ratings. n = 0..100000; ratings = -10^9..10^9. Equal ratings impose no extra constraint.',
 'First line: lowercase ASCII string, possibly empty, up to 100000 characters. Second line: K = 0..100000. Positions are zero based; equality at exactly K is allowed.',
 '`n`, followed by n positive values. n = 1..100000; values = 1..10^9. Arithmetic and totals use signed 64-bit integers.',
 '`n`, followed by n rows `start end`. n = 0..100000; 0 <= start <= end <= 10^9. Zero-length intervals use room ID 0 and consume no room.',
 '`n`, followed by n ordered positive weights. n = 1..256; weight = 1..10^9. Leaf order is fixed and weights belong to leaves, rather than internal search keys.',
 '`n`, followed by n nonempty lowercase ASCII words, each 1..64 characters. n = 1..12. Duplicate and contained words are removed before either algorithm.'
]
IDEAS=[
 'The sheet does not specify how consumption advances time. This implementation explicitly assumes continuous consumption at one weight unit per time unit, starting at t=0 with no idle time. An amount x consumed from time s contributes (v/w)*x - lambda*x*(s+x/2). Items may be skipped, and unused capacity is allowed. For fixed amounts, put larger decay rates first. Optimise the amounts jointly by enumerating the faces of a bounded concave quadratic programme, rather than asserting that a density sort solves the fractional-choice problem.',
 'Put all positive frequencies in a min-heap. Repeatedly merge the two lightest nodes, then traverse the tree to obtain code lengths. Sort symbols by (length, ASCII symbol), increment the previous code and shift when the length increases. The printed codebook is canonical; singleton input uses the one-bit code 0.',
 'Sort stations by distance. Keep every reachable, unused station in a max-heap keyed by fuel. When current reach is below D, take the largest available fuel; if the heap is empty, the journey is impossible. Selections are retrospective bookkeeping, and are finally reported in valid travel order. The paper title is retained exactly, but its body asks for minimum stops with fixed starting fuel, which is the task solved here.',
 'Put all lengths in a min-heap. Remove the two smallest, add their sum to the total, and return the new stick to the heap. Record each merge so the final cost can be replayed.',
 'Initialise each allocation to one. A left-to-right pass enforces constraints from the left neighbour. A right-to-left pass takes the maximum of that allocation and the lower bound imposed by the right neighbour. Sum the resulting componentwise minimum allocation.',
 'Choose the remaining character with highest frequency among those currently available. After placing it at position p, keep it in a FIFO cooldown queue until p+K. Release ready characters before choosing the next position. If no character is available while work remains, report impossibility. Equal frequencies use ASCII order for deterministic output.',
 'Double odd values to put every element at its largest reachable even representative. Maintain a max-heap and the smallest current value. Record the current range, halve the maximum while it is even, and stop when the maximum is odd. Reconstruct a witness inside the best interval by halving each normalised original until it is no larger than the recorded upper bound.',
 'Process nonempty meetings in start order. A min-heap stores each allocated room with its current end time. Reuse the earliest-ending room if it has ended; otherwise allocate one new room. Preserve original input indices to return the complete assignment in input order.',
 'Use the genuine three-phase Hu-Tucker procedure. Two active nodes are compatible when no remaining original leaf lies strictly between them; artificial nodes do not block compatibility. Merge the minimum-sum compatible pair with a consistent leftmost tie rule. Compute each original leaf depth in the combination tree, then reconstruct an alphabetic tree from those depths using an ordered stack. Scanning all compatible pairs is a transparent simulation, not the fastest implementation.',
 'Repeatedly merge the directed pair with maximum suffix-prefix overlap; ties choose the first pair in current order. Separately solve subset DP: dp[mask][last] is the shortest superstring length covering mask and ending in last. Reconstruct both strings, verify every original input is contained, and report the observed ratio. The exact comparator is intentionally limited to twelve words.'
]
PROOFS=[
 'For fixed x_i and x_j, swapping adjacent i,j changes value by (lambda_i-lambda_j)*x_i*x_j, so descending lambda is optimal. In this order the objective is rho^T x - (1/2)x^T H x with H_ij=min(lambda_i,lambda_j). H is positive semidefinite because min(a,b)=integral 1[t<=a]1[t<=b] dt. Thus the objective is concave. Enumerating zero, upper-bound and free coordinates, with capacity either slack or active, includes an optimal face. A singular free system can be moved to a boundary without changing the objective, so an optimum is represented by a nonsingular subface. The floating-point solver checks feasibility with tolerances; a separate gradient-based global optimality gap validates test cases.',
 'In an optimal prefix tree, the two least frequent symbols can be assigned deepest sibling leaves by exchange. Contracting them reduces the same optimisation problem to one fewer leaf, proving the repeated minimum-pair merge. Canonicalisation preserves every length and hence the weighted cost; the generated codes are checked for the prefix-free property.',
 'Whenever extra fuel is required, any feasible continuation must have chosen some already reachable station. Replacing that choice by the available station with maximum fuel cannot reduce reachable distance and uses the same number of stops. Apply this exchange repeatedly. An empty available heap before reaching D is an impossibility certificate. Selected station IDs are replayed in physical travel order.',
 'The two shortest sticks can occupy deepest sibling leaves of an optimal merge tree: placing smaller weights at larger depths cannot increase cost. Contract those siblings and solve the reduced instance. The resulting induction is the same minimum-pair argument as Huffman coding.',
 'Every feasible allocation must be at least the ascending-run bound from the left and the descending-run bound from the right. Their pointwise maximum satisfies every neighbour constraint. It is therefore componentwise no greater than any feasible allocation and minimises the sum.',
 'Equal characters cannot be reused before their release position. Among released types, using the most frequent remaining type protects the tightest future demand; the uniform-spacing exchange argument yields the standard maximum-frequency scheduling rule. The independent feasibility criterion is (maximum_count-1)*max(K,1)+number_of_maximum_types <= length. Every reported arrangement is also replayed to check its multiset and distances.',
 'Each element has a finite descending chain of reachable values from its normalised maximum to its odd base. Only decreasing a current maximum can shrink the upper endpoint; decreasing any other element cannot lower that maximum and may lower the minimum. Enumerating successive maximum reductions therefore examines a best range. Once the maximum is odd it cannot decrease further. The witness chooses a legal value from each chain inside the best recorded interval.',
 'If the earliest-ending allocated room has not ended, all allocated rooms overlap the new start, so one additional room is unavoidable. If it has ended, reuse requires no new room. Thus each allocation matches a simultaneous-overlap lower bound and the final count is minimum.',
 'Hu-Tucker compatible-pair contraction yields optimal alphabetic leaf depths, and its final reconstruction preserves those depths while restoring leaf order. The compatibility test is essential: merely choosing the smallest adjacent pair is a different, generally suboptimal algorithm. Independent interval DP computes OPT(i,j)=sum(weights[i..j])+min_k(OPT(i,k)+OPT(k+1,j)) and checks the simulation cost; ordered prefix codes and weighted depths are also replayed.',
 'After removing contained words, an optimal superstring can be represented by an ordering of the remaining words with maximum suffix-prefix overlaps. The subset recurrence tries every possible predecessor, so it obtains the optimum for the finite instance. Maximum-overlap greedy restricts this choice and is a heuristic. A sample ratio and small exhaustive checks provide instance evidence, not a universal approximation theorem.'
]
ANALYSES=[
 'There are at most 2*3^n face/capacity cases, each requiring an O(n^3) linear solve and feasibility check. Time is O(3^n n^3); workspace is O(n^2). The recorded work counts faces plus ordering comparisons, not all arithmetic operations. n<=8 is deliberate.',
 'Heap construction by insertion and n-1 merges take O(n log n). Ordering the codebook takes O(n log n); writing B total code bits takes O(B). Time is O(n log n+B), space O(n+B). A maximally skewed codebook can have B=Theta(n^2).',
 'Station sorting and at most n heap insertions/removals give O(n log n) time and O(n) space. The counter includes sort and heap comparisons.',
 'At most n-1 merges perform a constant number of O(log n) heap operations: O(n log n) time and O(n) space including the merge trace.',
 'Two passes and a sum take Theta(n) time. The witness uses O(n) space. Exactly 2*max(n-1,0) neighbour comparisons are counted.',
 'For m characters and sigma distinct types, heap scheduling takes O(m log sigma) time, conventionally O(m) for sigma=1, and O(m+sigma) space including input, output and the cooldown queue. Sigma<=26 in this implementation.',
 'Each normalised value can be halved at most O(log M) times, for O(n log M) reductions, each using O(log n) heap work. Time is O(n log M log n) and space O(n), using log(n+1) for the singleton convention. Witness reconstruction costs O(n log M) without copying the whole array after every step.',
 'Sorting and heap assignment give O(n log n) time and O(n) space. The independent end-before-start sweep uses the same half-open convention.',
 'A direct scan considers at most O(k^2) compatible pairs at active size k. Summing for k=n..2 gives O(n^3) time. Tree, stack, codes and active nodes use O(n) workspace excluding emitted text. Emitting all code bits can take O(n^2), within the cubic time bound. n<=256 is the simulation limit.',
 'Let L be the maximum intermediate string length, at most n*l for maximum input length l. The naive overlap routine costs O(L^2); O(n^3) directed-pair checks give a safe greedy bound O(n^3 L^2). Exact DP costs O(2^n n^2+n^2 l^2) time and O(2^n n+n^2+nL) space including strings. The work counter combines greedy overlap probes and exact-overlap precomputation; exact DP transitions are counted separately.'
]
RESULTS=[
 'The sample consumes two units of item 1 followed by two units of item 3, skips item 2 and obtains integrated value 9.000000 with used capacity 4.',
 'The sample codebook has weighted cost 224 bits and mean length 2.24 bits per symbol. The lengths and canonical bit strings agree with an independent optimum.',
 'The sample reaches distance 110 using two stops, stations 1 and 4 in travel order. The body of the question is answered with fixed initial fuel 10.',
 'The sample merges 2+3, 4+5, 6+7 and 9+13. Their costs sum to the minimum total 49.',
 'Ratings [1,3,4,5,2] yield candies [1,2,3,4,1], whose minimum total is 11. Eight neighbour checks agree with 2(n-1).',
 'For aaadbbcc and K=3 the sample produces abcabcad. Its character counts are unchanged and all equal-letter gaps satisfy the requirement.',
 'The sample achieves minimum deviation 3 using the legal witness [4,2,5,5,3] in interval [2,5]. Four maximum halvings suffice.',
 'The six sample meetings need three rooms; IDs [1,2,2,3,2,3] give a conflict-free assignment. Reuse at a shared endpoint is allowed.',
 'The sample has optimal alphabetic cost 153. Codes 000,001,01,1000,1001,1010,1011,11 preserve the input leaf order and replay the weighted cost.',
 'On abb, bba and bbc, deterministic greedy gives abbabbc of length 7, while exact DP returns bbabbc of length 6. The observed ratio is 7/6; this example shows non-optimality, not a disproof of a 2-approximation bound.'
]

SOURCES={9:'Hu and Tucker, SIAM Journal on Applied Mathematics (1971): https://epubs.siam.org/doi/10.1137/0121057 . Peter Shor\'s MIT notes: https://math.mit.edu/~djk/18.310/Lecture-Notes/PeterShor-hu-tucker.html .',
10:'The question sheet cites Hiroki Shibata\'s September 2026 preprint, Disproving the Greedy Superstring Conjecture: https://arxiv.org/abs/2609.01365 . Version 1 reports a ratio approaching 9/4, but the sheet also says the claim has not been officially validated. This lab does not independently certify that claim. The local exact comparison stands on its own.'}
